POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "Kevin",
    "email": "kevin@gmail.com",
    "password": "12345",
    "confPassword":"12345",
    "role":"admin"
}

GET http://localhost:5000/users
Content-Type: application/json